spring:
  profiles:
     active: qa
     
  jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
  dataSource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account-management
    username: root
    password: admin

security:
  basic:
    enabled: false